# Generated by tools/packaging for v1.0.0.
cask "godl-desktop" do
  version "1.0.0"
  sha256 "e50a8a83fdb93560a9cb99bcac4a488b8158e91313400a40db5bbdd64ca4ea85"

  url "https://github.com/zichuanxu/godl/releases/download/v#{version}/godl-desktop_#{version}_macos_universal.dmg"
  name "godl"
  desc "Fast download manager with a menu bar app"
  homepage "https://github.com/zichuanxu/godl"

  depends_on macos: ">= :monterey"

  app "godl.app"

  zap trash: "~/Library/Application Support/godl"

  caveats <<~EOS
    godl is free and unsigned: it is not notarized by Apple. On first launch,
    if macOS says it cannot verify the developer, open System Settings >
    Privacy & Security and choose "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/godl.app
  EOS
end
