# Generated by tools/packaging for v1.0.1.
cask "nimget-desktop" do
  version "1.0.1"
  sha256 "e6e6650f2bb18361d7b9d7d11b19ccf039ec0638c4e7fd57dcd4413a2c9fff9b"

  url "https://github.com/zichuanxu/nimget/releases/download/v#{version}/nimget-desktop_#{version}_macos_universal.dmg"
  name "NimGet"
  desc "Lightweight, open-source download manager built in Go"
  homepage "https://github.com/zichuanxu/nimget"

  depends_on macos: ">= :monterey"

  app "NimGet.app"

  zap trash: "~/Library/Application Support/nimget"

  caveats <<~EOS
    NimGet is free and unsigned: it is not notarized by Apple. On first launch,
    if macOS says it cannot verify the developer, open System Settings >
    Privacy & Security and choose "Open Anyway", or run:
      xattr -dr com.apple.quarantine /Applications/NimGet.app
  EOS
end
