# Generated by tools/packaging for v1.0.0.
class Godl < Formula
  desc "Fast, cross-platform download manager: command-line client and service"
  homepage "https://github.com/zichuanxu/godl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/zichuanxu/godl/releases/download/v1.0.0/godl_1.0.0_darwin_arm64.tar.gz"
      sha256 "1265e45503c55a6903abf29dde31f749164fe03fa35b4fdbad66859e60728337"
    end
    on_intel do
      url "https://github.com/zichuanxu/godl/releases/download/v1.0.0/godl_1.0.0_darwin_amd64.tar.gz"
      sha256 "79b341e1f50258f4bab3197334f27097ab1b223def84d1168537d2f87951e302"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zichuanxu/godl/releases/download/v1.0.0/godl_1.0.0_linux_arm64.tar.gz"
      sha256 "b3e0851954d298a23f69fb388ac96411ec9d9105172a1f7244f769647720e76b"
    end
    on_intel do
      url "https://github.com/zichuanxu/godl/releases/download/v1.0.0/godl_1.0.0_linux_amd64.tar.gz"
      sha256 "2e0b06831df1517accb68bf11ab2688e99326703eecc367e4a83c930cb807ab9"
    end
  end

  def install
    bin.install "godl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/godl version")
  end
end
