# Generated by tools/packaging for v1.0.1.
class Nimget < Formula
  desc "Fast, cross-platform download manager: command-line client and service"
  homepage "https://github.com/zichuanxu/nimget"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/zichuanxu/nimget/releases/download/v1.0.1/nimget_1.0.1_darwin_arm64.tar.gz"
      sha256 "d3bba9c668aa0bcadbf3451f8be4e04be0d118e22dde4a40dc2654451d85a199"
    end
    on_intel do
      url "https://github.com/zichuanxu/nimget/releases/download/v1.0.1/nimget_1.0.1_darwin_amd64.tar.gz"
      sha256 "a1e37c6bbd807870d2bbb3cc4e750bbb37cbfaa909b21b1970089b62a22a8829"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zichuanxu/nimget/releases/download/v1.0.1/nimget_1.0.1_linux_arm64.tar.gz"
      sha256 "bb9f768f1caef6995c57fbecdb29a2f976eef305a156fd803103e938427793d1"
    end
    on_intel do
      url "https://github.com/zichuanxu/nimget/releases/download/v1.0.1/nimget_1.0.1_linux_amd64.tar.gz"
      sha256 "c431ba47eeb4fd5a8a94d469c722813e558b2f8a2fb89b1d70b07e1b2745ad88"
    end
  end

  def install
    bin.install "nimget"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nimget version")
  end
end
